name: squircle_study
description: Comparing different Squircle ShapeBorders
publish_to: 'none'
version: 1.3.2
environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # https://pub.dev/packages/cupertino_rounded_corners
  cupertino_rounded_corners: ^2.1.1

  # https://pub.dev/packages/figma_squircle
  # figma_squircle: ^0.5.3
  figma_squircle: # It was on 0.5.3 before being broken by Flutter 3.27.0 and later.
    git:
      url: https://github.com/Ax0elz/figma_squircle
      ref: 5f1ad5aaccdf31fc398fc141979ea845a0f45383 # The ref that fixes the issue

  # Color picker package, by Mike Rydstrom, rydmike.com (@rydmike).
  # Used for color selection in the app.
  # https://pub.dev/packages/flex_color_picker
  flex_color_picker: ^3.7.0

  # https://pub.dev/packages/flex_seed_scheme
  flex_seed_scheme: ^3.5.0

  flutter:
    sdk: flutter

  # https://pub.dev/packages/smooth_corner
  smooth_corner: ^1.1.1

  # https://pub.dev/packages/superellipse_shape
  superellipse_shape: ^0.2.0

  # Used for launching a WEB URL, by Google flutter.dev.
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
