name: squircle_study
description: Comparing different Squircle ShapeBorders
publish_to: 'none'
version: 1.2.0
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/cupertino_rounded_corners
  cupertino_rounded_corners: ^2.1.1

  # https://pub.dev/packages/figma_squircle
  figma_squircle: ^0.5.3

  # https://pub.dev/packages/flex_seed_scheme
  flex_seed_scheme: ^1.4.0

  flutter:
    sdk: flutter

  # https://pub.dev/packages/smooth_corner
  smooth_corner: ^1.1.0

  # https://pub.dev/packages/superellipse_shape
  superellipse_shape: ^0.2.0

  # Used for launching a WEB URL, by Google flutter.dev.
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
